/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor.de.temperatura;

import java.text.DecimalFormat;

/**
 *
 * @author AlumnoT
 */
public class Interfaz extends javax.swing.JFrame {

    private double conversion;
    private DecimalFormat decimal=new DecimalFormat("0.0");

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        campoTexto = new javax.swing.JTextField();
        rbCelsius = new javax.swing.JRadioButton();
        rbFarenheit = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        cbCelsius = new javax.swing.JCheckBox();
        cbFarenheit = new javax.swing.JCheckBox();
        cbKelvin = new javax.swing.JCheckBox();
        lCelsius = new javax.swing.JTextField();
        lFarenheit = new javax.swing.JTextField();
        lKelvin = new javax.swing.JTextField();
        lGrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de temperatura");
        setBackground(new java.awt.Color(102, 51, 255));

        campoTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTexto.setToolTipText("Introduzca la temperatura");

        buttonGroup1.add(rbCelsius);
        rbCelsius.setText("ºC");
        rbCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelsiusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFarenheit);
        rbFarenheit.setText("ºF");
        rbFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFarenheitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKelvin);
        rbKelvin.setText("ºK");
        rbKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelvinActionPerformed(evt);
            }
        });

        cbCelsius.setText("ºC");
        cbCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCelsiusActionPerformed(evt);
            }
        });

        cbFarenheit.setText("ºF");
        cbFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFarenheitActionPerformed(evt);
            }
        });

        cbKelvin.setText("ºK");
        cbKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelvinActionPerformed(evt);
            }
        });

        lCelsius.setEditable(false);
        lCelsius.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lFarenheit.setEditable(false);
        lFarenheit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lKelvin.setEditable(false);
        lKelvin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lGrados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCelsius)
                                .addGap(18, 18, 18)
                                .addComponent(rbFarenheit)
                                .addGap(18, 18, 18)
                                .addComponent(rbKelvin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCelsius)
                                .addGap(18, 18, 18)
                                .addComponent(cbFarenheit)
                                .addGap(18, 18, 18)
                                .addComponent(cbKelvin))
                            .addComponent(lCelsius)
                            .addComponent(lKelvin)
                            .addComponent(lFarenheit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lGrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCelsius)
                    .addComponent(rbFarenheit)
                    .addComponent(rbKelvin))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCelsius)
                    .addComponent(cbFarenheit)
                    .addComponent(cbKelvin))
                .addGap(18, 18, 18)
                .addComponent(lCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFarenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFarenheitActionPerformed
        cbFarenheit.setSelected(false);
        lFarenheit.setText(" ");
        cbCelsius.setSelected(false);
        lCelsius.setText(" ");
        cbKelvin.setSelected(false);
        lKelvin.setText(" ");
        cbFarenheit.setVisible(false);
        lFarenheit.setVisible(false);
        lCelsius.setVisible(rootPaneCheckingEnabled);
        lKelvin.setVisible(rootPaneCheckingEnabled);
        cbCelsius.setVisible(rootPaneCheckingEnabled);
        cbKelvin.setVisible(rootPaneCheckingEnabled);
        lGrados.setText("ºF");
    }//GEN-LAST:event_rbFarenheitActionPerformed

    private void rbCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelsiusActionPerformed
        cbFarenheit.setSelected(false);
        lFarenheit.setText(" ");
        cbCelsius.setSelected(false);
        lCelsius.setText(" ");
        cbKelvin.setSelected(false);
        lKelvin.setText(" ");
        cbFarenheit.setVisible(rootPaneCheckingEnabled);
        cbCelsius.setVisible(false);
        lFarenheit.setVisible(rootPaneCheckingEnabled);
        lCelsius.setVisible(false);
        lKelvin.setVisible(rootPaneCheckingEnabled);
        cbKelvin.setVisible(rootPaneCheckingEnabled);
        lGrados.setText("ºC");
    }//GEN-LAST:event_rbCelsiusActionPerformed

    private void rbKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKelvinActionPerformed
        cbFarenheit.setSelected(false);
        lFarenheit.setText(" ");
        cbCelsius.setSelected(false);
        lCelsius.setText(" ");
        cbKelvin.setSelected(false);
        lKelvin.setText(" ");
        cbFarenheit.setVisible(rootPaneCheckingEnabled);
        cbCelsius.setVisible(rootPaneCheckingEnabled);
        cbKelvin.setVisible(false);
        lFarenheit.setVisible(rootPaneCheckingEnabled);
        lCelsius.setVisible(rootPaneCheckingEnabled);
        lKelvin.setVisible(false);
        lGrados.setText("ºK");
    }//GEN-LAST:event_rbKelvinActionPerformed

    private void cbCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCelsiusActionPerformed
        if (rbCelsius.isSelected()){
            lCelsius.setText(campoTexto.getText());
        }
        if (rbFarenheit.isSelected()) {
            conversion = (Double.parseDouble(campoTexto.getText()) - 32) / 1.8;
            lCelsius.setText(""+decimal.format(conversion));
        }
        if (rbKelvin.isSelected()) {
            conversion = Double.parseDouble(campoTexto.getText()) - 273.15;
            lCelsius.setText(""+decimal.format(conversion));
        }
        if (cbCelsius.isSelected()==false){
            lCelsius.setText("");
        }
    }//GEN-LAST:event_cbCelsiusActionPerformed

    private void cbFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFarenheitActionPerformed
        if (rbCelsius.isSelected()){
            conversion=(Double.parseDouble(campoTexto.getText())*1.8)+32;
            lFarenheit.setText(""+decimal.format(conversion));
        }
        if (rbFarenheit.isSelected()) {
            lFarenheit.setText(campoTexto.getText());
        }
        if (rbKelvin.isSelected()) {
            conversion = ((Double.parseDouble(campoTexto.getText()) - 273.15) *1.8 )+32;
            lFarenheit.setText(""+decimal.format(conversion));
        }
        if (cbFarenheit.isSelected()==false){
            lFarenheit.setText("");
        }
    }//GEN-LAST:event_cbFarenheitActionPerformed

    private void cbKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelvinActionPerformed
        if (rbCelsius.isSelected()){
            conversion = Double.parseDouble(campoTexto.getText()) + 273.15;
            lKelvin.setText(""+decimal.format(conversion));
        }
        if (rbFarenheit.isSelected()) {
            conversion = ((Double.parseDouble(campoTexto.getText()) - 32) / 1.8)+273.15;;
            lKelvin.setText(""+decimal.format(conversion));
        }
        if (rbKelvin.isSelected()) {
            lKelvin.setText(campoTexto.getText());
        }
        if (cbKelvin.isSelected()==false){
            lKelvin.setText("");
        }
    }//GEN-LAST:event_cbKelvinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JCheckBox cbCelsius;
    private javax.swing.JCheckBox cbFarenheit;
    private javax.swing.JCheckBox cbKelvin;
    private javax.swing.JTextField lCelsius;
    private javax.swing.JTextField lFarenheit;
    private javax.swing.JLabel lGrados;
    private javax.swing.JTextField lKelvin;
    private javax.swing.JRadioButton rbCelsius;
    private javax.swing.JRadioButton rbFarenheit;
    private javax.swing.JRadioButton rbKelvin;
    // End of variables declaration//GEN-END:variables
}
